"""Builds the generated bits of the site.

    python3 tools/build.py

- Lists the files in assets/illustrations/ in manifest.js, so the home page
  only loads illustrations that exist (the rest keep their doodle placeholder).
  Run it again after adding illustrations.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


ILLOS = ROOT / 'assets/illustrations'
ILLOS.mkdir(parents=True, exist_ok=True)
files = sorted(f.name for f in ILLOS.iterdir() if f.suffix.lower() in {'.png', '.webp', '.jpg', '.jpeg', '.svg', '.avif'})
(ILLOS / 'manifest.js').write_text('// Generated by tools/build.py: illustrations that exist on disk.\nwindow.ILLOS = ' + repr(files).replace("'", '"') + ';\n')
print(f'illustrations manifest: {len(files)} file(s)')
