import puppeteer from 'puppeteer-core';
import fs from 'node:fs';
import path from 'node:path';
const [dir, out, cols='3'] = process.argv.slice(2);
const files = fs.readdirSync(dir).filter(f => /\.(png|jpe?g|webp|svg)$/i.test(f)).sort();
const html = `<body style="margin:0;background:#888;display:grid;grid-template-columns:repeat(${cols},1fr);gap:6px;padding:6px">${files.map(f=>`<div style="font:12px sans-serif;color:#fff"><img src="file://${path.resolve(dir,f)}" style="width:100%;display:block">${f}</div>`).join('')}</body>`;
fs.writeFileSync(out + '.html', html);
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args:['--allow-file-access-from-files'] });
const p = await b.newPage(); await p.setViewport({ width: 1500, height: 800 });
await p.goto('file://' + path.resolve(out + '.html'), { waitUntil: 'load' });
await p.screenshot({ path: out, fullPage: true }); await b.close();
